target:
  url: "http://testphp.vulnweb.com"
  timeout: 10
  threads: 50

bruteforce:
  enabled: false
  delay: 0.0

crawler:
  depth: 2

wordlists:
  subdomains: "wordlists/subdomains.txt"
  directories: "wordlists/directories.txt"
  users: "wordlists/users.txt"
  passwords: "wordlists/passwords.txt"

scanners:
  sqli:
    payloads: "wordlists/sqli_payloads.txt"
  xss:
    payloads: "wordlists/xss_payloads.txt"
